### ISSUE TITLE
F-Droid reproducible build failed

### ISSUE THREAD

**Issue by linsui** [aeonBTC/Mempal#6]
https://gitlab.com/fdroid/checkupdates-bot-fdroiddata/-/jobs/10065304840

Could you add

```
    buildTypes {
        release {
            vcsInfo.include false
        }
    }
```

to remove the vcs info or build the apk from a normal git repo? Thanks!

**Comment by aeonBTC** [comment]
My mistake, should be fixed now. Thank you.

**Comment by linsui** [comment]
Thanks!

**Comment by licaon-kter** [comment]
can we reopen? https://gitlab.com/fdroid/checkupdates-bot-fdroiddata/-/jobs/11573135630#L420

difflog: [mem16.log](https://github.com/user-attachments/files/22660933/mem16.log)

maybe cleaning up caches and stuff helps?

**Comment by aeonBTC** [comment]
> can we reopen? https://gitlab.com/fdroid/checkupdates-bot-fdroiddata/-/jobs/11573135630#L420
> 
> difflog: [mem16.log](https://github.com/user-attachments/files/22660933/mem16.log)
> 
> maybe cleaning up caches and stuff helps?

I cleaned and rebuilt, try again?

**Comment by licaon-kter** [comment]
still fails :( https://gitlab.com/fdroid/fdroiddata/-/jobs/11590132705#L425

**Comment by aeonBTC** [comment]
Im not sure what's causing the failure, im using the same build process ive used in all previous version.

**Comment by aeonBTC** [comment]
It should be fixed now, please try again. @licaon-kter

**Comment by licaon-kter** [comment]
Nope https://gitlab.com/fdroid/fdroiddata/-/jobs/11608592798#L423

**Comment by aeonBTC** [comment]
Should be fixed with the new v2.0 build.
